/* Dingel Hafizia — Students: exact 3-sheet workflow */
import {getCollection,addDocument,updateDocument,deleteDocument,setDocument} from "./firestore.js";
const V=document.getElementById("view"),MONTHS=["APRL","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC","JAN","FEB","MAR"],CLASSES=["HIFZ","MAKTAB","ADNA ALIF"];
let S=[],tab="master",payments=[],year=ay();
function ay(){let d=new Date(),y=d.getMonth()>=3?d.getFullYear():d.getFullYear()-1;return y+"-"+String(y+1).slice(-2)}
function today(){let d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
const E=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const M=v=>new Intl.NumberFormat("en-IN",{maximumFractionDigits:2}).format(Number(v)||0);
const name=s=>s.name||s.studentName||"Unnamed",roll=s=>s.roll??s.rol??s.rollNo??s.studentId??"—",father=s=>s.fatherName||s.father||s.guardian||"—",phone=s=>s.phone||s.number||s.phoneNumber||"—",rawFee=s=>s.monthly??s.monthlyFee??s.feeCategory??s.fee??"-";
function fee(s){let r=String(rawFee(s)).trim().toUpperCase();if(!r||r==="-"||r==="ATIM"||r==="N RSD"||r==="N_RSD"||r==="POOR")return 0;let n=Number(String(rawFee(s)).replace(/[^0-9.]/g,""));return Number.isFinite(n)?n:0}
function feeText(s){let r=String(rawFee(s)).trim().toUpperCase(),n=fee(s);return n?"₹"+M(n):r==="ATIM"?"ATIM":r==="POOR"?"POOR":(r==="N RSD"||r==="N_RSD")?"N RSD":"-"}
const active=s=>String(s.status||"Active").toLowerCase()!=="inactive",orphan=s=>String(rawFee(s)).trim().toUpperCase()==="ATIM"||s.studentType==="Orphan";
function toast(t,err=false){let r=document.getElementById("toastRoot");if(!r)return;r.textContent=t;r.className=err?"toast error":"toast";setTimeout(()=>{r.textContent="";r.className=""},2500)}
async function load(){try{S=await getCollection("students")}catch(e){S=[];console.error(e)}window.__dhStudents=S}
function nextRoll(){let nums=S.map(s=>Number(s.roll??s.rol??s.rollNo)).filter(Number.isFinite);return String((nums.length?Math.max(...nums):0)+1)}
function tabs(){return `<div class="sheet-tabs"><button class="sheet-tab ${tab==="master"?"active":""}" data-tab="master">1. Master Student List</button><button class="sheet-tab ${tab==="active"?"active":""}" data-tab="active">2. Active Students List</button><button class="sheet-tab ${tab==="monthly"?"active":""}" data-tab="monthly">3. Monthly Collection & Due</button></div>`}
function top(){return `<div class="page-header"><div><h3>Students Details</h3><p>Google Sheet-এর ৩টি worksheet অনুযায়ী সম্পূর্ণ student ও fee management</p></div><button class="btn primary" id="addStudentBtn">＋ Add Student</button></div>${tabs()}`}
function common(){document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=async()=>{tab=b.dataset.tab;await load();render()});document.getElementById("addStudentBtn")?.addEventListener("click",()=>studentForm());document.getElementById("emptyAdd")?.addEventListener("click",()=>studentForm())}
function actions(){document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>viewStudent(b.dataset.view));document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>studentForm(b.dataset.edit));document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>delStudent(b.dataset.del))}
function master(){let q=(document.getElementById("sheetSearch")?.value||"").toLowerCase(),rows=S.filter(s=>!q||[roll(s),name(s),father(s),s.address||"",s.class||"",phone(s),rawFee(s)].join(" ").toLowerCase().includes(q)),target=S.reduce((a,s)=>a+fee(s),0);V.innerHTML=`<div class="content sheet-page">${top()}<div class="sheet-summary"><div><small>Total Registered Students</small><b>${S.length}</b></div><div><small>Total Potential Monthly Fees</small><b>₹${M(target)}</b></div><div><small>Active</small><b>${S.filter(active).length}</b></div><div><small>Inactive / Left</small><b>${S.filter(s=>!active(s)).length}</b></div></div><div class="sheet-toolbar"><div class="student-search"><span>⌕</span><input id="sheetSearch" placeholder="Search name, roll, father, address or phone" value="${E(q)}"></div><button class="btn outline" id="sheetRefresh">↻ Refresh</button></div><div class="card sheet-card"><div class="card-header"><h3>DINGEL HAFIZIA MADRASAH STUDENTS DETAILS</h3><span>${rows.length} / ${S.length}</span></div><div class="sheet-scroll"><table class="sheet-table"><thead><tr><th>SL</th><th>ROL</th><th>Student Name</th><th>Father's Name</th><th>ADDRESS</th><th>Class</th><th>Number</th><th>MONTHLY</th><th>Options</th></tr></thead><tbody>${rows.length?rows.map((s,i)=>masterRow(s,i)).join(""):empty(9)}</tbody></table></div></div></div>`;common();actions();document.getElementById("sheetSearch")?.addEventListener("input",master);document.getElementById("sheetRefresh")?.addEventListener("click",async()=>{await load();master()})}
function masterRow(s,i){return `<tr><td>${i+1}</td><td><b>${E(roll(s))}</b></td><td><div class="sheet-person"><span>${E(name(s).slice(0,2).toUpperCase())}</span><b>${E(name(s))}</b></div></td><td>${E(father(s))}</td><td>${E(s.address||"—")}</td><td><span class="sheet-badge">${E(s.class||"—")}</span></td><td>${E(phone(s))}</td><td><b>${E(feeText(s))}</b></td><td><button data-view="${E(s.id)}">👁</button><button data-edit="${E(s.id)}">✎</button><button data-del="${E(s.id)}">🗑</button></td></tr>`}
function activePage(){let all=S.filter(active),q=(document.getElementById("sheetSearch")?.value||"").toLowerCase(),rows=all.filter(s=>!q||[roll(s),name(s),father(s),s.address||"",s.class||"",phone(s),rawFee(s)].join(" ").toLowerCase().includes(q)),target=all.reduce((a,s)=>a+fee(s),0);V.innerHTML=`<div class="content sheet-page">${top()}<div class="sheet-summary"><div><small>Total Active Students</small><b>${all.length}</b></div><div><small>Total Active Monthly Fee Target</small><b>₹${M(target)}</b></div><div><small>ATIM / Free</small><b>${all.filter(orphan).length}</b></div><div><small>Classes</small><b>${new Set(all.map(s=>s.class).filter(Boolean)).size}</b></div></div><div class="sheet-toolbar"><div class="student-search"><span>⌕</span><input id="sheetSearch" placeholder="Search active student, roll, guardian or phone" value="${E(q)}"></div><button class="btn outline" id="sheetRefresh">↻ Refresh</button></div><div class="card sheet-card"><div class="card-header"><h3>PRESENT STUDENTS DETAILS</h3><span>${rows.length} / ${all.length}</span></div><div class="sheet-scroll"><table class="sheet-table"><thead><tr><th>S.L</th><th>ROL</th><th>STUDENTS</th><th>GUARDIAN</th><th>ADDRESS</th><th>CLASS</th><th>PH NO</th><th>FEES</th><th>Options</th></tr></thead><tbody>${rows.length?rows.map((s,i)=>activeRow(s,i)).join(""):empty(9)}</tbody></table></div></div></div>`;common();actions();document.getElementById("sheetSearch")?.addEventListener("input",activePage);document.getElementById("sheetRefresh")?.addEventListener("click",async()=>{await load();activePage()})}
function activeRow(s,i){return `<tr><td>${i+1}</td><td><b>${E(roll(s))}</b></td><td><div class="sheet-person"><span>${E(name(s).slice(0,2).toUpperCase())}</span><b>${E(name(s))}</b></div></td><td>${E(father(s))}</td><td>${E(s.address||"—")}</td><td><span class="sheet-badge">${E(s.class||"—")}</span></td><td>${E(phone(s))}</td><td><b>${E(feeText(s))}</b>${orphan(s)?'<small class="free-note">Free</small>':''}</td><td><button data-view="${E(s.id)}">👁</button><button data-edit="${E(s.id)}">✎</button><button data-del="${E(s.id)}">🗑</button></td></tr>`}
function empty(n){return `<tr><td colspan="${n}"><div class="student-empty"><div class="empty-icon">👨‍🎓</div><h4>No student records</h4><p>Add students to populate this sheet.</p><button class="btn primary small" id="emptyAdd">＋ Add Student</button></div></td></tr>`}
async function loadPayments(){try{payments=await getCollection("monthlyPayments")}catch(e){payments=[];console.error(e)}}
const pay=(id,m)=>payments.find(p=>p.studentId===id&&p.month===m&&p.academicYear===year);
function monthly(){loadPayments().then(()=>{let q=(document.getElementById("sheetSearch")?.value||"").toLowerCase(),all=S.filter(active),rows=all.filter(s=>!q||[roll(s),name(s),phone(s)].join(" ").toLowerCase().includes(q));let sum=MONTHS.map(m=>{let c=0,d=0,t=0;rows.forEach(s=>{let b=fee(s),p=pay(s.id,m),payed=Math.min(b,Number(p?.paidAmount||0));t+=b;c+=payed;d+=Math.max(0,b-payed)});return{c,d,t}});V.innerHTML=`<div class="content sheet-page monthly-sheet-page">${top()}<div class="monthly-toolbar"><div><label>Academic Year</label><select><option>${year}</option></select></div><div class="student-search"><span>⌕</span><input id="sheetSearch" placeholder="Search active student, roll or phone" value="${E(q)}"></div><button class="btn outline" id="sheetRefresh">↻ Refresh</button></div><div class="fee-legend"><span><i class="paid-dot"></i> ✓ Paid</span><span><i class="partial-dot"></i> Partial</span><span><i class="unpaid-dot"></i> Unpaid / Due</span><span>Month cell-এ tap করে fee collect করুন</span></div><div class="card sheet-card"><div class="card-header"><h3>MONTHLY COLLECTION & DUE TRACKER</h3><span>${rows.length} Active Students</span></div><div class="sheet-scroll fee-matrix-scroll"><table class="sheet-table fee-matrix"><thead><tr><th>ROL</th><th>STUDENTS</th><th>PH NO</th><th>FEES</th>${MONTHS.map(m=>`<th>${m}</th>`).join("")}</tr></thead><tbody>${rows.length?rows.map(s=>feeRow(s)).join(""):empty(16)}</tbody><tfoot><tr class="summary-collected"><th colspan="4">Total Collected (জমা হয়েছে)</th>${sum.map(x=>`<td>₹${M(x.c)}</td>`).join("")}</tr><tr class="summary-due"><th colspan="4">Total Outstanding / Due (বাকি আছে)</th>${sum.map(x=>`<td>₹${M(x.d)}</td>`).join("")}</tr><tr class="summary-target"><th colspan="4">Target Total (সর্ব মোট)</th>${sum.map(x=>`<td>₹${M(x.t)}</td>`).join("")}</tr></tfoot></table></div></div></div>`;document.getElementById("sheetSearch")?.addEventListener("input",monthly);document.getElementById("sheetRefresh")?.addEventListener("click",monthly);document.querySelectorAll("[data-fee]").forEach(b=>b.onclick=()=>collect(b.dataset.id,b.dataset.month));common()})}
function feeRow(s){return `<tr><td><b>${E(roll(s))}</b></td><td><div class="sheet-person"><span>${E(name(s).slice(0,2).toUpperCase())}</span><b>${E(name(s))}</b></div></td><td>${E(phone(s))}</td><td><b>${E(feeText(s))}</b></td>${MONTHS.map(m=>{let p=pay(s.id,m),b=fee(s),a=Number(p?.paidAmount||0),cls=!a?"unpaid":a<b?"partial":"paid",txt=!a?"—":b&&a<b?"₹"+M(a):"✓ paid";return `<td><button class="fee-cell ${cls}" data-fee="1" data-id="${E(s.id)}" data-month="${m}">${txt}</button></td>`}).join("")}</tr>`}
function modal(c){document.getElementById("modalRoot").innerHTML=`<div class="modal-backdrop" id="dhModal"><div class="modal student-modal">${c}</div></div>`;document.getElementById("dhModal").onclick=e=>{if(e.target.id==="dhModal")closeModal()}}
function closeModal(){document.getElementById("modalRoot").innerHTML=""}
function field(l,n,v,t="text",req=false,extra=""){return `<div class="form-group"><label>${l}${req?' <span class="required-star">*</span>':''}</label><input name="${n}" type="${t}" value="${E(v)}" ${req?"required":""} ${extra}></div>`}
function feeOptions(s){let r=String(rawFee(s)).trim().toUpperCase();let custom=!['-','ATIM','POOR','N RSD','N_RSD'].includes(r);return `<option value="-" ${r==='-'?'selected':''}>-</option><option value="ATIM" ${r==='ATIM'?'selected':''}>ATIM</option><option value="POOR" ${r==='POOR'?'selected':''}>POOR</option><option value="N RSD" ${r==='N RSD'||r==='N_RSD'?'selected':''}>N RSD</option><option value="CUSTOM" ${custom?'selected':''}>CUSTOM</option>`}
function studentForm(id){let s=id?S.find(x=>x.id===id):{},r=id?roll(s):nextRoll(),ad=id?(s.admissionDate||s.admission_date||today()):today(),customFee=String(rawFee(s)).trim().toUpperCase();if(id&&['-','ATIM','POOR','N RSD','N_RSD'].includes(customFee))customFee="";modal(`<div class="card-header"><div><h3>${id?"Edit Student":"Add Student"}</h3><p class="text-muted">Roll No ও Admission Date automatic</p></div><button class="icon-btn" id="x">×</button></div><form id="sf"><div class="card-body"><div class="student-form-grid"><div class="form-group"><label>ROL / Roll Number</label><input value="${E(r)}" readonly></div>${field("Student Name","name",name(s)==="Unnamed"?"":name(s),"text",true)}${field("Father's Name","fatherName",father(s)==="—"?"":father(s))}${field("Number / Phone","phone",phone(s)==="—"?"":phone(s),"tel")}<div class="form-group"><label>Class <span class="required-star">*</span></label><select name="class" required>${CLASSES.map(c=>`<option value="${c}" ${s.class===c?"selected":""}>${c}</option>`).join("")}</select></div><div class="form-group"><label>MONTHLY</label><select id="monthlyType" name="monthlyType">${feeOptions(s)}</select><input id="customFee" name="customFee" type="number" min="0" step="0.01" placeholder="Enter your own monthly amount" value="${E(customFee)}" style="display:none;margin-top:8px"></div><div class="form-group full-width"><label>ADDRESS</label><input name="address" value="${E(s.address||"")}"></div><div class="form-group"><label>Admission Date</label><input value="${E(ad)}" readonly></div></div><div class="form-footer"><button type="button" class="btn outline" id="cancel">Cancel</button><button class="btn primary">${id?"Save Changes":"Add Student"}</button></div></div></form></div>`);let mt=document.getElementById("monthlyType"),cf=document.getElementById("customFee"),sync=()=>{cf.style.display=mt.value==="CUSTOM"?"block":"none"};sync();mt.onchange=sync;document.getElementById("x").onclick=closeModal;document.getElementById("cancel").onclick=closeModal;document.getElementById("sf").onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));let monthly=d.monthlyType==="CUSTOM"?String(d.customFee||"").trim():d.monthlyType;if(d.monthlyType==="CUSTOM"&&(!d.customFee||Number(d.customFee)<0))return toast("Enter a valid custom monthly fee",true);d.roll=r;d.rol=r;d.name=d.name.trim();d.fatherName=d.fatherName.trim();d.guardian=d.fatherName;d.phone=d.phone.trim();d.number=d.phone;d.address=d.address.trim();d.monthly=monthly||"-";d.admissionDate=ad;d.studentType=d.monthly==="ATIM"?"Orphan":"General";d.status="Active";delete d.monthlyType;delete d.customFee;try{id?await updateDocument("students",id,d):await addDocument("students",d);closeModal();toast(id?"Student updated":"Student added");await load();render()}catch(err){console.error(err);toast("Save failed. Check Firestore permissions.",true)}}}
function viewStudent(id){let s=S.find(x=>x.id===id);if(!s)return;modal(`<div class="card-header"><div><h3>Student Details</h3><p>${E(name(s))} · Roll ${E(roll(s))}</p></div><button class="icon-btn" id="x">×</button></div><div class="card-body"><div class="student-detail-grid">${[["ROL",roll(s)],["Student Name",name(s)],["Father's Name",father(s)],["ADDRESS",s.address||"—"],["Class",s.class||"—"],["Number",phone(s)],["MONTHLY",feeText(s)],["Admission Date",s.admissionDate||"—"]].map(x=>`<div class="student-detail-item"><small>${x[0]}</small><strong>${E(x[1])}</strong></div>`).join("")}</div><div class="form-footer"><button class="btn outline" id="close">Close</button><button class="btn primary" id="edit">Edit Student</button></div></div>`);document.getElementById("x").onclick=closeModal;document.getElementById("close").onclick=closeModal;document.getElementById("edit").onclick=()=>{closeModal();studentForm(id)}}
async function delStudent(id){let s=S.find(x=>x.id===id);if(!s||!confirm(`Delete ${name(s)}?`))return;try{await deleteDocument("students",id);toast("Student deleted");await load();render()}catch(e){toast("Delete failed",true)}}
async function collect(id,month){let s=S.find(x=>x.id===id),p=pay(id,month),b=fee(s),old=Number(p?.paidAmount||0),due=Math.max(0,b-old);modal(`<div class="card-header"><div><h3>Collect Fee — ${month}</h3><p>${E(name(s))} · Roll ${E(roll(s))}</p></div><button class="icon-btn" id="x">×</button></div><form id="cf"><div class="card-body"><div class="collect-summary"><div><small>Monthly Fee</small><b>${feeText(s)}</b></div><div><small>Already Paid</small><b>₹${M(old)}</b></div><div><small>Current Due</small><b>₹${M(due)}</b></div></div><div class="form-group"><label>Payment Amount (₹)</label><input id="amt" name="amount" type="number" min="0" step="0.01" value="${b?due:0}" ${b?"":"disabled"}></div><div id="preview" class="collect-preview"></div><div class="form-footer"><button type="button" class="btn outline" id="cancel">Cancel</button><button class="btn primary">Save Payment</button></div></div></form>`);let a=document.getElementById("amt"),pr=document.getElementById("preview"),up=()=>{let add=Number(a?.value||0),t=old+add;pr.innerHTML=!b?'<span class="status-badge active">FREE / NO COLLECTION</span>':t>=b?'<span class="status-badge active">✓ PAID — No Due</span>':`<span class="status-badge partial">PARTIAL — Due ₹${M(b-t)}</span>`};up();a?.addEventListener("input",up);document.getElementById("x").onclick=closeModal;document.getElementById("cancel").onclick=closeModal;document.getElementById("cf").onsubmit=async e=>{e.preventDefault();let add=Number(a?.value||0),total=old+add;if(add<0||(b&&total>b))return toast("Payment cannot exceed monthly fee",true);let d={studentId:id,studentName:name(s),roll:roll(s),month,academicYear:year,baseFee:b,paidAmount:total,dueAmount:Math.max(0,b-total),status:!b?"FREE":total>=b?"PAID":total?"PARTIAL":"UNPAID",updatedAt:new Date().toISOString()};try{p?await setDocument("monthlyPayments",p.id,d):await addDocument("monthlyPayments",d);closeModal();toast("Payment saved");await monthly()}catch(err){console.error(err);toast("Payment save failed",true)}}}
function render(){if(tab==="master")master();else if(tab==="active")activePage();else monthly()}
function intercept(){let n=document.getElementById("nav"),b=n?.querySelector('[data-page="students"]');if(b&&!b.dataset.sheet){b.dataset.sheet="1";b.onclick=async()=>{tab="master";await load();render()}}}
const ob=new MutationObserver(intercept);ob.observe(document.getElementById("nav"),{childList:true,subtree:true});window.addEventListener("dh:auth",async()=>{intercept();await load();if(document.querySelector('[data-page="students"].active'))render()});window.__dhReloadStudents=async()=>{await load();render()};setTimeout(intercept,500);